### ISSUE TITLE
Streaming stop not sending

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-android#101]
I ran a test in the server and, apparently, there are scenarios where not all the state changes are registered in the database. 

Execute the following test. 

1 - start recording
2 - start streaming
3 - stop streaming
4 - pause
5 - resume
6 - start streaming
7 - logout

Check if all the states get registered in the history screen

**Comment by martelli** [comment]
Reproduced the suggested steps and verified the following information in the report log:

RECORDING_ONLINE
STREAMING       
RECORDING_ONLINE
PAUSED          
RECORDING_ONLINE
STREAMING       
NOT_LOGGED      

During the processes, I was unable to open the report screen, due to some file name issues. This has been fixed (commit 297feca).
